import javax.swing.JSlider;
public class BMR extends javax.swing.JFrame {

    public BMR() {
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        MaleButton = new javax.swing.JRadioButton();
        FemaleButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KiloC = new javax.swing.JRadioButton();
        KiloJ = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        AgeText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MiffinAlgo = new javax.swing.JRadioButton();
        HarrisAlgo = new javax.swing.JRadioButton();
        CalculateButton = new javax.swing.JButton();
        ResultText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        HSlider = new javax.swing.JSlider();
        WSlider = new javax.swing.JSlider();
        HLabel = new javax.swing.JLabel();
        WLabel = new javax.swing.JLabel();
        ErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(MaleButton);
        MaleButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        MaleButton.setText("Male");
        MaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(FemaleButton);
        FemaleButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        FemaleButton.setText("Female");
        FemaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Height (cm)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Age (15-80)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Weight (kg)");

        buttonGroup2.add(KiloC);
        KiloC.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        KiloC.setText("Kilocalories");
        KiloC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KiloCActionPerformed(evt);
            }
        });

        buttonGroup2.add(KiloJ);
        KiloJ.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        KiloJ.setText("Kilojoules");
        KiloJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KiloJActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Result Type:");

        AgeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Equation:");

        buttonGroup3.add(MiffinAlgo);
        MiffinAlgo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        MiffinAlgo.setText("Mifflin-St Jeor");
        MiffinAlgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiffinAlgoActionPerformed(evt);
            }
        });

        buttonGroup3.add(HarrisAlgo);
        HarrisAlgo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        HarrisAlgo.setText("Harris-Benedict");
        HarrisAlgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HarrisAlgoActionPerformed(evt);
            }
        });

        CalculateButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CalculateButton.setText("Calculate");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        ResultText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultTextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("------->");

        HSlider.setMajorTickSpacing(10);
        HSlider.setMaximum(200);
        HSlider.setMinorTickSpacing(1);
        HSlider.setPaintLabels(true);
        HSlider.setPaintTicks(true);
        HSlider.setValue(0);
        HSlider.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                HSliderAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                HSliderAncestorRemoved(evt);
            }
        });
        HSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                HSliderStateChanged(evt);
            }
        });

        WSlider.setMajorTickSpacing(10);
        WSlider.setMaximum(200);
        WSlider.setMinorTickSpacing(1);
        WSlider.setPaintLabels(true);
        WSlider.setPaintTicks(true);
        WSlider.setValue(0);
        WSlider.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                WSliderAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        WSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                WSliderStateChanged(evt);
            }
        });

        HLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        HLabel.setText("0");
        HLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                HLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        WLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        WLabel.setText("0");
        WLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                WLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        ErrorLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(MaleButton)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MiffinAlgo)
                                        .addGap(18, 18, 18)
                                        .addComponent(HarrisAlgo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(KiloC)
                                        .addGap(34, 34, 34)
                                        .addComponent(KiloJ))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(FemaleButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(ResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ErrorLabel)
                                .addGap(181, 181, 181))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(HSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(WSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(691, 691, 691)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaleButton)
                    .addComponent(FemaleButton))
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(HSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(WSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(WLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KiloC)
                    .addComponent(KiloJ)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MiffinAlgo)
                    .addComponent(HarrisAlgo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ErrorLabel)
                        .addGap(88, 88, 88))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleButtonActionPerformed
  
    }//GEN-LAST:event_MaleButtonActionPerformed

    private void FemaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleButtonActionPerformed
        
        
    }//GEN-LAST:event_FemaleButtonActionPerformed

    private void KiloCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KiloCActionPerformed

    }//GEN-LAST:event_KiloCActionPerformed

    private void KiloJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KiloJActionPerformed
  
    }//GEN-LAST:event_KiloJActionPerformed

    private void MiffinAlgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiffinAlgoActionPerformed
        
    }//GEN-LAST:event_MiffinAlgoActionPerformed

    private void HarrisAlgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HarrisAlgoActionPerformed
      
    }//GEN-LAST:event_HarrisAlgoActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        
        double A = Double.parseDouble(AgeText.getText());
        double H = Double.parseDouble(HLabel.getText());
        double W = Double.parseDouble(WLabel.getText());
        double BMR = 0;
        
        if(A>80 || A<15){
            ErrorLabel.setText("Age Error");
        }
        else{
            
            if(MaleButton.isSelected()){
               if(KiloJ.isSelected()){
                     BMR = BMR * 4.1868;
                   if(MiffinAlgo.isSelected()){
                     BMR = (10*W) + (6.25*H) - (5*A) + 5;
               }
               else if(HarrisAlgo.isSelected()){
                   BMR = (13.397*W) + (4.799*H) - (5.677*A) + 88.362;
               }
              }
               else{
                   if(MaleButton.isSelected()){
                       if(MiffinAlgo.isSelected()){
                            BMR = (10*W) + (6.25*H) - (5*A) + 5;
                       }
                       else if(HarrisAlgo.isSelected()){
                            BMR = (13.397*W) + (4.799*H) - (5.677*A) + 88.362; 
                       }
                   }
               }
            }
            
            else if(FemaleButton.isSelected()){
                if(KiloJ.isSelected()){
                       BMR = BMR * 4.1868;
                  if(MiffinAlgo.isSelected()){
                       BMR = (10*W) + (6.25*H) - (5*A) - 161;
                }
                else if(HarrisAlgo.isSelected()){
                       BMR = (9.247*W) + (3.098*H) - (4.330*A) + 447.593;
                }  
              }
                else{
                    if(MiffinAlgo.isSelected()){
                       BMR = (10*W) + (6.25*H) - (5*A) - 161; 
                }
                else if(HarrisAlgo.isSelected()){
                       BMR = (9.247*W) + (3.098*H) - (4.330*A) + 447.593;
                }  
              }
               
            }
            
        }
        
        String OutputBMR = String.format("%.2f", BMR);
        ResultText.setText(OutputBMR);
        
        
       
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void AgeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTextActionPerformed
        
    }//GEN-LAST:event_AgeTextActionPerformed

    private void HSliderAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_HSliderAncestorAdded
        
    }//GEN-LAST:event_HSliderAncestorAdded

    private void WSliderAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_WSliderAncestorAdded
       
    }//GEN-LAST:event_WSliderAncestorAdded

    private void WSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_WSliderStateChanged
         String W = ""+((JSlider)evt.getSource()).getValue();
         WLabel.setText(W);
    }//GEN-LAST:event_WSliderStateChanged
    
    private void HLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_HLabelAncestorAdded
        
    }//GEN-LAST:event_HLabelAncestorAdded

    private void WLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_WLabelAncestorAdded
       
    }//GEN-LAST:event_WLabelAncestorAdded

    private void HSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_HSliderStateChanged
         String H = ""+((JSlider)evt.getSource()).getValue();
         HLabel.setText(H);
    }//GEN-LAST:event_HSliderStateChanged

    private void HSliderAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_HSliderAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_HSliderAncestorRemoved

    private void ResultTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultTextActionPerformed
       
    }//GEN-LAST:event_ResultTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeText;
    private javax.swing.JButton CalculateButton;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JRadioButton FemaleButton;
    private javax.swing.JLabel HLabel;
    private javax.swing.JSlider HSlider;
    private javax.swing.JRadioButton HarrisAlgo;
    private javax.swing.JRadioButton KiloC;
    private javax.swing.JRadioButton KiloJ;
    private javax.swing.JRadioButton MaleButton;
    private javax.swing.JRadioButton MiffinAlgo;
    private javax.swing.JTextField ResultText;
    private javax.swing.JLabel WLabel;
    private javax.swing.JSlider WSlider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
